[package]
name = "quasicrystals"
version = "1.1"
authors = ["ertdfgcb <odaypaul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
clap = "3.0.0-beta.1"
